ha:
  image:
    repository: ghcr.io/home-assistant/home-assistant
    tag: stable

  ingress:
    enabled: true
    hosts:
      - host: "" # will be overriden in homelab-secrets
        paths:
          - path: /
            pathType: Prefix

  configuration:
    enabled: true
    trusted_proxies:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 100.64.0.0/10

  persistence:
    enabled: true
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  hostNetwork: true

  nodeSelector:
    kubernetes.io/hostname: pi-01
