image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: stable

ingress:
  enabled: true
  host: ha.joluc.de

persistence:
  enabled: true
  storageClass: local-path
  size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

hostNetwork: true
