postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "" # will be overriden in homelab-secrets
        database: "homelab"
        # We will create users/dbs via initdb scripts or manually
        # For simplicity in homelab, we can use initdbScripts

  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path

    # K8up backup annotations
    podAnnotations:
      k8up.io/backupcommand: sh -c 'PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall -U postgres --clean'
      k8up.io/file-extension: .sql

    # initdb scripts extracted to secrets repo
    initdb:
      scripts: {} # will be overriden in homelab-secrets

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 1Gi

  # Disable internal metrics for now to save resources, or enable if needed
  metrics:
    enabled: true
