apiVersion: v2
name: cph-metro-exporter
description: Copenhagen Metro Exporter wrapper chart
type: application
version: 1.0.1
appVersion: "1.0.1"
dependencies:
  - name: cph-metro-exporter
    version: "1.0.1"
    repository: "oci://ghcr.io/joluc/charts"
