{{- range .Values.cluster.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  {{ .secretKey }}: {{ index $.Values.userPasswords .name | required (printf "userPasswords.%s is required" .name) }}
{{- end }}
