operator:
  enabled: true
  manager:
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

cluster:
  enabled: true
  cluster:
    name: opensearch
    general:
      version: 3.5.0
      httpPort: 9200
      vendor: opensearch
      serviceName: opensearch-service
      monitoring:
        enable: true
        scrapeInterval: 30s
        pluginUrl: https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.5.0.0/prometheus-exporter-3.5.0.0.zip
        tlsConfig:
          insecureSkipVerify: true

    nodePools:
      - component: nodes
        replicas: 1
        diskSize: "30Gi"
        roles:
          - "cluster_manager"
          - "data"
          - "ingest"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        persistence:
          pvc:
            storageClass: local-path
            accessModes:
              - ReadWriteOnce

    security:
      tls:
        transport:
          generate: true
          perNode: true
        http:
          generate: true

    dashboards:
      enabled: true
      replicas: 1
      version: 3.5.0
      enableTls: false

    ingress:
      dashboards:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        hosts: [] # Will be set in homelab-secrets
