apiVersion: config.joluc.de/v1alpha1
kind: ClusterSpecterConfig
metadata:
  name: global
spec:
  templates:
    logs:
      url: {{ .Values.clusterConfig.templates.logs.url | quote }}
      description: "View logs in OpenSearch"

    metrics:
      url: {{ .Values.clusterConfig.templates.metrics.url | quote }}
      description: "Explore metrics in Grafana"

    dashboard:
      url: {{ .Values.clusterConfig.templates.dashboard.url | quote }}
      description: "View namespace dashboard"

  defaultLabels:
    environment: {{ .Values.clusterConfig.environment | quote }}
