apiVersion: v2
name: vaultwarden
version: 1.0.0
description: Vaultwarden self-hosted Bitwarden server

dependencies:
  - name: vaultwarden
    version: 1.3.0
    repository: https://gissilabs.github.io/charts
