vaultwarden:
  # Persistence for vault data
  persistence:
    enabled: true
    storageClass: standard
    size: 5Gi

  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    host: "" # will be overriden in homelab-secrets

  # Resource limits
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Environment variables
  env:
    DATABASE_URL: "" # will be overriden in homelab-secrets
    DOMAIN: "" # will be overriden in homelab-secrets
    SIGNUPS_ALLOWED: "false"  # Disable after initial setup
    WEBSOCKET_ENABLED: "true"
