image:
  repository: ghcr.io/pocket-id/pocket-id
  tag: v2

ingress:
  enabled: true
  host: "" # will be overriden in homelab-secrets

persistence:
  enabled: false  # Disabled when using external Postgres database
  storageClass: local-path
  size: 1Gi

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  APP_URL: "" # will be overriden in homelab-secrets
  TRUST_PROXY: "false" # will be overriden in homelab-secrets
  ENCRYPTION_KEY: "" # will be overriden in homelab-secrets
  DB_CONNECTION_STRING: "" # will be overriden in homelab-secrets - set to postgres:// URL for external database
