image:
  repository: stonith404/pocket-id
  tag: latest

ingress:
  enabled: true
  host: auth.joluc.de

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  PUBLIC_APP_URL: https://auth.joluc.de
