apiVersion: v2
name: perses
version: 1.0.0
description: Perses lightweight Prometheus dashboards

dependencies:
  - name: perses
    version: 0.23.2
    repository: https://perses.github.io/helm-charts
