dbCredentials:
  dbEncryptionKey: ""  # will be overridden in homelab-secrets
  dbUrl: ""  # will be overridden in homelab-secrets

homarr:
  envSecrets:
    dbEncryption:
      existingSecret: "homarr-db-secret"
      key: "db-encryption-key"
    dbCredentials:
      existingSecret: "homarr-db-secret"
      dbUrlKey: "db-url"

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: "" # will be overridden in homelab-secrets
        paths:
          - path: /
            pathType: Prefix

  persistence:
    data:
      enabled: true
      storageClass: local-path
      size: 2Gi
    config:
      enabled: true
      storageClass: local-path
      size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
