homarr:
  database:
    type: postgresql

  env:
    AUTH_PROVIDERS: "oidc"
    AUTH_OIDC_ISSUER: ""  # will be overridden in homelab-secrets
    AUTH_OIDC_CLIENT_NAME: "Pocket ID"
    AUTH_OIDC_AUTO_LOGIN: "true"
    AUTH_OIDC_SCOPE_OVERWRITE: "openid email profile"

  envSecrets:
    dbEncryption:
      existingSecret: "homarr-db-secret"
      key: "db-encryption-key"
    dbCredentials:
      existingSecret: "homarr-db-secret"
      dbUrlKey: "db-url"
    authOidcCredentials:
      existingSecret: "homarr-oidc-secret"
      oidcClientId: "oidc-client-id"
      oidcClientSecret: "oidc-client-secret"

  dbCredentials:
    dbEncryptionKey: ""  # will be overridden in homelab-secrets
    dbUrl: ""  # will be overridden in homelab-secrets

  oidcCredentials:
    clientId: ""  # will be overridden in homelab-secrets
    clientSecret: ""  # will be overridden in homelab-secrets

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: "" # will be overridden in homelab-secrets
        paths:
          - path: /
            pathType: Prefix

  persistence:
    data:
      enabled: true
      storageClass: local-path
      size: 2Gi
    config:
      enabled: true
      storageClass: local-path
      size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
