apiVersion: v1
kind: ConfigMap
metadata:
  name: perses-project
  namespace: perses
  labels:
    perses.dev/resource: "true"
data:
  project.yaml: |
    kind: Project
    metadata:
      name: infra
    spec:
      display:
        name: Infrastructure
        description: Infrastructure monitoring with Kubernetes, Prometheus, and Node Exporter dashboards
