image:
  repository: lissy93/dashy
  tag: "3.1.1"  # Use specific version to avoid rebuild on startup

ingress:
  enabled: true
  host: "" # will be overriden in homelab-secrets

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 200m
