image:
  repository: lissy93/dashy
  tag: latest

ingress:
  enabled: true
  host: dash.joluc.de

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi

resources:
  requests:
    memory: 150Mi
    cpu: 100m
  limits:
    memory: 300Mi
    cpu: 200m
