{{- if and .Values.persistence.homarrTrustedCerts.enabled (eq .Values.persistence.homarrTrustedCerts.type "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homarr.fullname" . }}-trusted-certificates-secret
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.persistence.homarrTrustedCerts.certificates }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
