all:
  children:
    gateways:
      hosts:
        gateway-01:
          ansible_host: "{{ gateway_ip }}"
    control_plane:
      hosts:
        control-01:
          ansible_host: "{{ control_plane_ip }}"
    workers:
      hosts:
        pi-01:
          ansible_host: "{{ pi_01_ip }}"
        pi-02:
          ansible_host: "{{ pi_02_ip }}"
        pi-03:
          ansible_host: "{{ pi_03_ip }}"
