apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command: ["sh", "-c", "if [ ! -f /app/user-data/conf.yml ]; then echo '---' > /app/user-data/conf.yml; echo 'pageTitle: Homelab' >> /app/user-data/conf.yml; fi"]
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /app/user-data
            {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["yarn", "start"]
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 8080
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /app/user-data
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        {{- end }}
