apiVersion: v2
name: badevand-exporter
description: Badevand Exporter wrapper chart
type: application
version: 0.2.2
appVersion: "0.2.2"
dependencies:
  - name: badevand-exporter
    version: "0.2.2"
    repository: "oci://ghcr.io/joluc/charts"
