badevand-exporter:
  nameOverride: "badevand-exporter"
  fullnameOverride: "badevand-exporter"

  image:
    repository: ghcr.io/joluc/badevand-exporter
    tag: "0.2.1"

  config:
    sites: []
    include: ""
    exclude: ""
    interval: "30s"
    cacheTTL: "30m"
    logLevel: "info"

  serviceMonitor:
    enabled: true
    labels:
      prometheus: kube-prometheus
    interval: 1h

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
