apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  users.xml: |
    <clickhouse>
      <users>
        <{{ .Values.auth.username }}>
          <password>{{ .Values.auth.password }}</password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </{{ .Values.auth.username }}>
      </users>
    </clickhouse>
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS plausible_events_db;
