apiVersion: v2
name: metrics-proxy
description: Metrics proxy wrapper chart
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
  - name: metrics-proxy
    version: "0.2.0"
    repository: "oci://ghcr.io/joluc/charts"
