apiVersion: v1
kind: Secret
metadata:
  name: homarr-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-encryption-key: {{ .Values.dbCredentials.dbEncryptionKey | quote }}
  db-url: {{ .Values.dbCredentials.dbUrl | quote }}
