apiVersion: v1
kind: Secret
metadata:
  name: homarr-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-encryption-key: {{ .Values.homarr.dbCredentials.dbEncryptionKey | quote }}
  db-url: {{ .Values.homarr.dbCredentials.dbUrl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: homarr-oidc-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  oidc-client-id: {{ .Values.homarr.oidcCredentials.clientId | quote }}
  oidc-client-secret: {{ .Values.homarr.oidcCredentials.clientSecret | quote }}
