minecraft:
  # Run on VPS (edge-compute node)
  nodeSelector:
    node_role: edge-compute

  # Minecraft server type
  minecraftServer:
    eula: "TRUE"
    version: "LATEST"
    type: "PAPER"
    difficulty: normal
    maxPlayers: 20
    motd: "" # will be overriden in homelab-secrets
    pvp: true
    onlineMode: true
    memory: 2G

  # Persistence for world data
  persistence:
    dataDir:
      enabled: true
      storageClass: local-path
      size: 10Gi

  # Service with LoadBalancer for K3s ServiceLB
  minecraftService:
    type: LoadBalancer
    loadBalancerIP: 10.0.10.25
    port: 25565
    externalTrafficPolicy: Local

  # Resource limits
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 3Gi

  # Backups with Velero
  podAnnotations:
    backup.velero.io/backup-volumes: datadir
