image:
  repository: linuxserver/unifi-controller
  tag: latest

ingress:
  enabled: true
  host: "" # will be overriden in homelab-secrets

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

env:
  PUID: "1000"
  PGID: "1000"
