unifi:
  image:
    repository: linuxserver/unifi-controller
    tag: latest

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: unifi.joluc.de
          paths:
            - path: /

  persistence:
    config:
      enabled: true
      storageClass: local-path
      size: 10Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
