openclaw:
  nameOverride: "krabbe"
  fullnameOverride: "krabbe"

  image:
    tag: "2026.2.25"

  config:
    agents:
      defaults:
        model:
          primary: "anthropic/claude-sonnet-4-20250514"
        thinkingDefault: "low"
        timeoutSeconds: 600
    browser:
      cdpUrl: "http://localhost:9222"
    gateway:
      mode: "local"
      controlUi:
        allowedOrigins:
          - "https://krabbe.joluc.de"
    integrations:
      telegram:
        enabled: true

  ingress:
    enabled: true
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: ImplementationSpecific
