global:
  security:
    allowInsecureImages: true

clickhouse:
  image:
    registry: docker.io
    repository: clickhouse/clickhouse-server
    tag: 24.3.3.102-alpine
    digest: ""

  auth:
    username: "default"
    password: "" # will be overridden in homelab-secrets

  # Single shard, single replica for homelab
  shards: 1
  replicaCount: 1

  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m

  # Init script to create Plausible database
  initdbScripts:
    init-plausible.sql: |
      CREATE DATABASE IF NOT EXISTS plausible_events_db;
