image:
  repository: clickhouse/clickhouse-server
  tag: 24.12.6.70-alpine

auth:
  username: "default"
  password: "" # will be overridden in homelab-secrets

persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 2Gi
    cpu: 1000m

service:
  httpPort: 8123
  tcpPort: 9000
