apiVersion: v2
name: specter
version: 0.1.0
description: Kubernetes operator for injecting diagnostic URLs into PrometheusRule alerts

dependencies:
  - name: specter
    version: 0.1.0
    repository: oci://ghcr.io/joluc/charts
