annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/homarr-labs/homarr docker tag to v1.54.0
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/homarr-labs/homarr
    - name: Chart Source
      url: https://github.com/homarr-labs/charts/tree/main/charts/homarr
  artifacthub.io/signKey: |
    fingerprint: 36F9A886ABA6AA4C1588B942E7EC1AA0EFD54840
    url: https://homarr-labs.github.io/charts/pgp_keys.asc
apiVersion: v2
appVersion: v1.54.0
description: A Helm chart to deploy homarr for Kubernetes
home: https://homarr-labs.github.io/charts/charts/homarr/
icon: https://raw.githubusercontent.com/homarr-labs/charts/refs/heads/main/charts/homarr/icon.svg
keywords:
- homarr
- dashboard
kubeVersion: '>=1.24.0-0'
maintainers:
- email: homarr-labs@proton.me
  name: oben01
name: homarr
sources:
- https://github.com/homarr-labs/homarr
type: application
version: 8.13.0
