apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-users-catalog
  namespace: {{ .Release.Namespace }}
data:
  users.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: {{ .Values.userId | default "guest" }}
    spec:
      profile:
        displayName: {{ .Values.displayName | default "Guest User" }}
        email: {{ .Values.userEmail | default "guest@example.com" }}
      memberOf: []
