apiVersion: v2
name: oauth2-proxy-thanos
description: OAuth2 Proxy for Thanos
type: application
version: 0.1.0

dependencies:
  - name: oauth2-proxy
    version: 10.7.0
    repository: https://oauth2-proxy.github.io/manifests
