apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: {{ .Values.thanosObjstore.bucket }}
      endpoint: {{ .Values.thanosObjstore.endpoint }}
      access_key: {{ .Values.thanosObjstore.accessKey }}
      secret_key: {{ .Values.thanosObjstore.secretKey }}
      insecure: {{ .Values.thanosObjstore.insecure }}
      signature_version2: false
      http_config:
        insecure_skip_verify: true
