apiVersion: v2
name: redis
version: 1.0.0
description: Redis instance for homelab (Paperless, etc.)

dependencies:
  - name: redis
    version: 28.0.15
    repository: https://charts.bitnami.com/bitnami
