apiVersion: v2
name: weather-exporter
description: Weather Exporter wrapper chart
type: application
version: 0.3.1
appVersion: "0.3.1"
dependencies:
  - name: weather-exporter
    version: "0.3.1"
    repository: "oci://ghcr.io/joluc/charts"
