weather-exporter:
  nameOverride: "weather-exporter"
  fullnameOverride: "weather-exporter"

  image:
    repository: ghcr.io/joluc/weather-exporter
    tag: "0.3.2"

  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      prometheus: kube-prometheus

  config:
    cities:
      - "Leipzig:51.33,12.37@dwd,dwd-pollen"
      - "Copenhagen:55.67,12.56@yr"

    providers:
      dwd:
        enabled: true
      dwdPollen:
        enabled: true
      yr:
        userAgent: ""
      openweathermap:
        enabled: false
        apiKey: ""

    cacheTTL: "5m"
    jsonLogs: false

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - arm64
