apiVersion: v2
name: jaeger
version: 1.0.0
description: Jaeger distributed tracing with OpenSearch backend

dependencies:
  - name: jaeger
    version: 4.12.0
    repository: https://jaegertracing.github.io/helm-charts
