apiVersion: v2
name: nextcloud
version: 1.0.0
description: Nextcloud - A safe home for all your data

dependencies:
  - name: nextcloud
    alias: app
    version: 9.2.5
    repository: https://nextcloud.github.io/helm
