app:
  # Override default values from the Nextcloud Helm chart
  # Ref: https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

  replicaCount: 1

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 10Gi

  # host, trustedDomains, and ingress settings are configured in homelab-secrets
