oauth2-proxy:
  config:
    clientID: "" # will be overridden in homelab-secrets
    clientSecret: "" # will be overridden in homelab-secrets
    cookieSecret: "" # will be overridden in homelab-secrets

  extraArgs:
    provider: oidc
    oidc-issuer-url: https://auth.joluc.de
    redirect-url: https://prometheus.joluc.de/oauth2/callback
    cookie-secure: true
    cookie-samesite: lax
    email-domain: "*"
    http-address: 0.0.0.0:4180
    skip-provider-button: true
    insecure-oidc-allow-unverified-email: true
    upstream: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090

  ingress:
    enabled: true
    className: traefik
    hosts:
      - "" # will be overridden in homelab-secrets
    path: /
    pathType: Prefix

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
