apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | quote }}
  {{- if .Values.smtp.enabled }}
  SMTP_USER_PWD: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if .Values.googleSearchConsole.enabled }}
  GOOGLE_CLIENT_SECRET: {{ .Values.googleSearchConsole.clientSecret | quote }}
  {{- end }}
