apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-main
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-main
    spec:
      initContainers:
        - name: {{ .Release.Name }}-main-init
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z -v -w30 {{ .Values.postgresql.host }} {{ .Values.postgresql.port }}
              do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 5
              done
              until nc -z -v -w30 {{ .Values.redis.host }} {{ .Values.redis.port }}
              do
                echo "Waiting for Redis to be ready..."
                sleep 5
              done
      containers:
        - name: {{ .Release.Name }}-main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: PAPERLESS_REDIS
              value: {{ .Values.redis.url }}
            - name: PAPERLESS_DBENGINE
              value: postgresql
            - name: PAPERLESS_DBHOST
              value: {{ .Values.postgresql.host }}
            - name: PAPERLESS_DBPORT
              value: {{ .Values.postgresql.port | quote }}
            - name: PAPERLESS_DBUSER
              value: {{ .Values.postgresql.username }}
            - name: PAPERLESS_DBPASS
              value: {{ .Values.postgresql.password }}
            - name: PAPERLESS_DBNAME
              value: {{ .Values.postgresql.database }}
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_URL
              value: {{ .Values.paperlessUrl }}
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: app_secret
            - name: USERMAP_UID
              value: "1000"
            - name: USERMAP_GID
              value: "1000"
            - name: PAPERLESS_APPS
              value: "allauth.socialaccount.providers.openid_connect"
            - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              value: {{ .Values.oidc.providers | toJson | quote }}
            - name: PAPERLESS_DISABLE_REGULAR_LOGIN
              value: "true"
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /usr/src/paperless/data
              subPath: data
            - name: {{ .Release.Name }}-data
              mountPath: /usr/src/paperless/media
              subPath: media
            - name: {{ .Release.Name }}-data
              mountPath: /usr/src/paperless/export
              subPath: export
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvc
