apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.hostNetwork | default false }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8123
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: config
              mountPath: /config
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        {{- end }}
