image:
  repository: adguard/adguardhome
  tag: v0.107.79

ingress:
  enabled: true
  host: "" # will be overriden in homelab-secrets

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 1Gi
  data:
    enabled: true
    storageClass: local-path
    size: 5Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: pi-01
