image:
  repository: adguard/adguardhome
  tag: latest

ingress:
  enabled: true
  host: dns.joluc.de

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 1Gi
  data:
    enabled: true
    storageClass: local-path
    size: 5Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
