image:
  repository: n8nio/n8n
  tag: latest

ingress:
  enabled: true
  host: n8n.joluc.de

persistence:
  enabled: true
  storageClass: local-path
  size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env:
  N8N_HOST: n8n.joluc.de
  N8N_PROTOCOL: https
  WEBHOOK_URL: https://n8n.joluc.de
  GENERIC_TIMEZONE: Europe/Berlin
