apiVersion: v2
name: thanos
description: Thanos long-term storage for Prometheus
version: 0.1.0
appVersion: "0.39.2"

dependencies:
  - name: thanos
    version: 17.3.1
    repository: https://charts.bitnami.com/bitnami
